addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "1.3.5")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.1.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"     % "1.0.1")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"     % "1.6.0")
